name: Suggestion
description: Help us improve with suggestions
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this suggestion form!
  - type: input
    id: suggestion
    attributes:
      label: Link to project
      description: Please share a link to your suggestion of a Read the Docs project (example or Real Life)
      placeholder: https://...
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe your suggesiton
      description: How and why is your suggestion useful to this community? Please indicate both where the project can be see and location of its source code project.
      placeholder: I wish to see project <xyz> here becuase it is used for...
    validations:
      required: true
