name: Suggestion
description: Improve the Awesome List by adding other awesome projects
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this suggestion form!
  - type: input
    id: suggestion
    attributes:
      label: Link to project
      description: Please share a link to your suggestion of a Read the Docs project
      placeholder: https://...
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe your suggesiton
      description: How and why is your suggestion useful to this community? What parts are awesome and can inspire other documentation authors?
      placeholder: I wish to see project <xyz> here because it is used for...
    validations:
      required: true
